/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import conectar.Conexion;
import controles.DatosMallaControl;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import tablas.DatosPeriodoSemestre;

/**
 *
 * @author Toshiba
 */
public class FormularioMalla extends javax.swing.JDialog {

    private static FrmMalla malla;
    private int pkMalla;
    private String activaMalla;
    double i, y;
    Conexion cc = Conexion.getInstance();
    Connection cn = cc.Conectar();
    DatosMallaControl mallaControl;
    ResultSet rs;
    DatosPeriodoSemestre dps;

    @SuppressWarnings("static-access")
    public FormularioMalla(FrmMalla parent, boolean modal) {
        this.malla = parent;
        this.setModal(modal);
        initComponents();
        mallaControl = new DatosMallaControl();
        cargarEspecialidad();
        cargarPeriodo();
        cargarSemestre();
        //dps = new DatosPeriodoSemestre();
    }

    @SuppressWarnings("static-access")
    public FormularioMalla(FrmMalla parent, boolean modal, Integer pkMalla) throws SQLException {
        this.malla = parent;
        this.setModal(modal);
        initComponents();
        this.pkMalla = pkMalla;
        mallaControl = new DatosMallaControl();

        cargarEspecialidad();
        cargarPeriodo();
        cargarSemestre();
        // dps = new DatosPeriodoSemestre();
        if (pkMalla > 0) {
            rs = mallaControl.consulta(pkMalla);
            String valRadio;
            while (rs.next()) {
                nombreMallaTxt.setText(rs.getString("nombre_malla"));
                semestreCmb.setSelectedIndex(Integer.valueOf(rs.getString("id_semestre")));
                especialidadCmb.setSelectedIndex(Integer.valueOf(rs.getString("id_especialidad")));
                periodoCmb.setSelectedIndex(Integer.valueOf(rs.getString("id_periodo")));
                valNotaSpinner.setValue(Integer.parseInt(rs.getString("por_nota")));
                valTutoSpinner.setValue(Integer.parseInt(rs.getString("por_tuto")));
                numHorasTxt.setText(rs.getString("num_hora"));
                valRadio = rs.getString("estado");

                switch (valRadio) {
                    case "AC":
                        actMallaRdb.setSelected(true);
                        break;
                    case "DE":
                        dscMallaRdb.setSelected(true);
                        break;
                }
            }
            cc.desconectar();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        estadoMalla = new javax.swing.ButtonGroup();
        nombreMallaTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        semestreCmb = new javax.swing.JComboBox();
        especialidadCmb = new javax.swing.JComboBox();
        periodoCmb = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        valNotaSpinner = new javax.swing.JSpinner();
        valTutoSpinner = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        numHorasTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        actMallaRdb = new javax.swing.JRadioButton();
        dscMallaRdb = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nombre de Malla");

        semestreCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECCIONE" }));
        semestreCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semestreCmbActionPerformed(evt);
            }
        });

        especialidadCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECCIONE" }));
        especialidadCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especialidadCmbActionPerformed(evt);
            }
        });

        periodoCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECCIONE" }));
        periodoCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periodoCmbActionPerformed(evt);
            }
        });

        jLabel2.setText("Semestre");

        jLabel3.setText("Especialidad");

        jLabel4.setText("Periodo");

        valNotaSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 1.0d));

        valTutoSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 1.0d));

        jLabel6.setText("Valor Total Nota");

        jLabel7.setText("Valor Total Tutoria");

        jLabel8.setText("Numero de Horas");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Estado Malla"));

        estadoMalla.add(actMallaRdb);
        actMallaRdb.setText("Activa ");
        actMallaRdb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actMallaRdbActionPerformed(evt);
            }
        });

        estadoMalla.add(dscMallaRdb);
        dscMallaRdb.setText("Desactivada");
        dscMallaRdb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dscMallaRdbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(actMallaRdb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(dscMallaRdb)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dscMallaRdb)
                    .addComponent(actMallaRdb))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jLabel9.setText("%");

        jLabel10.setText("%");

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(periodoCmb, 0, 113, Short.MAX_VALUE)
                            .addComponent(especialidadCmb, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(semestreCmb, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nombreMallaTxt))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(numHorasTxt)
                            .addComponent(valTutoSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(valNotaSpinner))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreMallaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(semestreCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(valNotaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(valTutoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(especialidadCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numHorasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(periodoCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jButton1)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void semestreCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semestreCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semestreCmbActionPerformed

    private void especialidadCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especialidadCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_especialidadCmbActionPerformed

    private void periodoCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periodoCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_periodoCmbActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Map datos = new HashMap();
        Calendar cal = Calendar.getInstance();
        datos.put("nombre_malla", nombreMallaTxt.getText().toUpperCase());
        datos.put("id1_semestre", semestreCmb.getSelectedIndex());
        datos.put("id1_especialidad", especialidadCmb.getSelectedIndex());
        datos.put("id1_periodo", dps.getId1Periodo());
        datos.put("por_nota", (double) valNotaSpinner.getValue());
        datos.put("por_tuto", (double) valTutoSpinner.getValue());
        datos.put("num_hora", numHorasTxt.getText());
        datos.put("estado", activaMalla);
        datos.put("fecha_creacion", cal.getTime());
        datos.put("porcentaje", "100");
        if (validaForm()) {
            try {
                if (pkMalla == 0) {
                    //camabiaEstado();
                    mallaControl.insertar("malla", datos);
                    this.dispose();

                } else {
                    mallaControl.actualizar("malla", "id_malla", 0.0, datos);
                    this.dispose();
                    JOptionPane.showMessageDialog(null, "Datos actualizados correctamente");
                }

            } catch (Exception e) {
                Logger.getLogger(FrmMalla.class.getName()).log(Level.SEVERE, null, e);
                JOptionPane.showMessageDialog(null, "Error", "Ocurrio un error al ingresar", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Error", "Campos Vacios", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed
//    private void camabiaEstado () throws SQLException{
//       int idmalla =mallaControl.cambioEstadoMalla();
//       String sql = "UPDATE malla SET estado = 'D' where idmalla="+idmalla+"";
//       cc=Conexion.getInstance();
//       cn=cc.Conectar();
//       Statement st = cn.createStatement();
//       st.executeUpdate(sql);
//    }
    private void actMallaRdbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actMallaRdbActionPerformed
        activaMalla = "A";
    }//GEN-LAST:event_actMallaRdbActionPerformed

    private void dscMallaRdbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dscMallaRdbActionPerformed
        activaMalla = "D";

    }//GEN-LAST:event_dscMallaRdbActionPerformed
    private boolean validaForm() {
        boolean respuesta = true;
        i = (double) valNotaSpinner.getValue();
        y = (double) valTutoSpinner.getValue();
        double valor = i + y;
        double numero = 100;
        if (nombreMallaTxt.getText().length() == 0) {
            respuesta = false;
        } else if (semestreCmb.getSelectedIndex() == 0) {
            respuesta = false;
        } else if (especialidadCmb.getSelectedIndex() == 0) {
            respuesta = false;
        } else if (periodoCmb.getSelectedIndex() == 0) {
            respuesta = false;
        }  else if (valor > numero) {
            respuesta = false;
        } else if (numHorasTxt.getText().length() == 0) {
            respuesta = false;
        } else if (actMallaRdb.isSelected() == false && dscMallaRdb.isSelected() == false) {
            respuesta = false;
        } else {
            respuesta = true;
        }

        return respuesta;
    }

    private void cargarSemestre() {

        try {
            String semes;
            rs = mallaControl.semestre();
            while (rs.next()) {
                semes = rs.getString("semestre");
                semestreCmb.addItem(semes);
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormularioMalla.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void cargarEspecialidad() {
        try {
            String espe;
            rs = mallaControl.especialidad();
            while (rs.next()) {
                espe = rs.getString("especialidad");
                especialidadCmb.addItem(espe);
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormularioMalla.class.getName()).log(Level.SEVERE, null, ex);

        }
    }

    private void cargarPeriodo() {
        try {
            rs = mallaControl.periodo();
            dps = new DatosPeriodoSemestre();
            while (rs.next()) {
                dps.setId1Periodo(Double.valueOf(rs.getString("id1_periodo")));
                dps.setPeriodo(rs.getString("periodo"));
                periodoCmb.addItem(dps);

            }
        } catch (SQLException ex) {
            Logger.getLogger(FormularioMalla.class.getName()).log(Level.SEVERE, null, ex);

        }
    }

    
    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioMalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioMalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioMalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioMalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormularioMalla dialog = new FormularioMalla(malla, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton actMallaRdb;
    private javax.swing.JRadioButton dscMallaRdb;
    private javax.swing.JComboBox especialidadCmb;
    private javax.swing.ButtonGroup estadoMalla;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombreMallaTxt;
    private javax.swing.JTextField numHorasTxt;
    private javax.swing.JComboBox periodoCmb;
    private javax.swing.JComboBox semestreCmb;
    private javax.swing.JSpinner valNotaSpinner;
    private javax.swing.JSpinner valTutoSpinner;
    // End of variables declaration//GEN-END:variables
}
