/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import conectar.Conexion;
import controles.DatosEspecialidadControl;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import tablas.DatosEspecialidad;

/**
 *
 * @author Ricardo
 */
public class FrmEspecialidad extends javax.swing.JInternalFrame {

    Conexion cc = Conexion.getInstance();
    Connection cn = cc.Conectar();
    private Double id1especialidad;
    public DefaultTableModel modelo;
    public static FormularioEspecialidad formularioEspecialidad;
    private List<DatosEspecialidad> listaEspcialidad;
    private ResultSet rs;

    public FrmEspecialidad() {
        super();
        initComponents();

        mostrarDatos();
       
    }

    public void mostrarDatos() {
        String[] col = {"CODIGO", "ESPECIALIDAD", "PKESPECIALIDAD"};
        String[][] data = {{"", "", ""}};
        modelo = new DefaultTableModel(data, col);
        modelo.setRowCount(0);
        tablaEspecialidad.setModel(modelo);
        
     //   tablaEspecialidad.getColumnModel().getColumn(2).setMaxWidth(0);
     //   tablaEspecialidad.getColumnModel().getColumn(2).setMinWidth(0);
      //  tablaEspecialidad.getTableHeader().getColumnModel().getColumn(2).setMaxWidth(0);
     //   tablaEspecialidad.getTableHeader().getColumnModel().getColumn(2).setMinWidth(0);
     //   tablaEspecialidad.setRowSorter(new TableRowSorter<TableModel>(modelo));
        
        mensaje.setText("ESPERE........");
       
        new Thread(new Runnable() {
            @Override
            public void run() {
                String idespecial = "";
                String especialidad = "";
                
                int i = 0;
                if (listaEspcialidad == null) {
                    listaEspcialidad = new ArrayList<>();
                } else {
                    listaEspcialidad.clear();
                }
                try {
                    DatosEspecialidadControl profesorConsulta = new DatosEspecialidadControl();
                    ResultSet rs = profesorConsulta.consultaOrdenada(0.0);
                    
                    while (rs.next()) {
                        Thread.sleep(5);
                        idespecial=rs.getString("id_especial");
                        especialidad=rs.getString("especialidad");
                         
                             modelo.insertRow(i++, new Object[]{
                                 idespecial,
                                 especialidad,
                                 rs.getObject("id1_especialidad")
                             });
                                            
                    }
                    
                } catch (SQLException | NullPointerException | InterruptedException ex) {
                    Logger.getLogger(FrmEspecialidad.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    try {
                        cc.desconectar();
                    } catch (SQLException ex) {
                        Logger.getLogger(FrmEspecialidad.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                mensaje.setText("TERMINADO....");

            }
        }).start();
        
    }

    public void mostrarFormularioEspecialdad() {
        try {
            formularioEspecialidad = new FormularioEspecialidad(FrmEspecialidad.this, true, id1especialidad);
        } catch (SQLException ex) {
            Logger.getLogger(FrmEspecialidad.class.getName()).log(Level.SEVERE, null, ex);
        }
        formularioEspecialidad.setLocationRelativeTo(FrmEspecialidad.this);
        formularioEspecialidad.setVisible(true);
        
        mostrarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEspecialidad = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        mensaje = new javax.swing.JLabel();

        setClosable(true);

        tablaEspecialidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaEspecialidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEspecialidadMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaEspecialidad);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/news_add.png"))); // NOI18N
        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        mensaje.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(248, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        id1especialidad = 0.0;
        mostrarFormularioEspecialdad();
   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tablaEspecialidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEspecialidadMouseClicked
      double i = tablaEspecialidad.getSelectedRow();
      int y = (int)Math.round(i);
      id1especialidad=(Double)tablaEspecialidad.getValueAt(y, 2);
      mostrarFormularioEspecialdad();
    }//GEN-LAST:event_tablaEspecialidadMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mensaje;
    public javax.swing.JTable tablaEspecialidad;
    // End of variables declaration//GEN-END:variables
}
