/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import control.CargarAlumnoWeb;
import javax.swing.JOptionPane;

/**
 *
 * @author Ricardo.Bravo
 */
public class ActualizacionDatos extends javax.swing.JInternalFrame {

    CargarAlumnoWeb alumno;

    public ActualizacionDatos() {
        initComponents();
        setLocation(360, 180);
        
        actualizacionBtn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actualizacionBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("ACTUALIZACION DE DATOS");

        actualizacionBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Sync.png"))); // NOI18N
        actualizacionBtn.setText("Iniciar Actualizacion");
        actualizacionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizacionBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Proceso para actualizacion de datos con la pagina web de la institucion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(72, 72, 72))
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(actualizacionBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(actualizacionBtn)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizacionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizacionBtnActionPerformed
        if (JOptionPane.showConfirmDialog(this, "¿Estimado usuario desea realizar la actualizacion de datos con la pagina web de la institucion", "Advertencia", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            cargar();
        }
    }//GEN-LAST:event_actualizacionBtnActionPerformed
    public void cargar() {
        new Thread(new Runnable() {
            final Thread th = Thread.currentThread();

            @Override
            public void run() {
                synchronized (th) {
                    alumno = new CargarAlumnoWeb();
                    alumno.start();
                }
            }
        }).start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizacionBtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
