/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import conectar.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import logica.MetodosGeneralesDao;
import modelo.Materia;

/**
 *
 * @author USER
 */
public class prueba extends javax.swing.JInternalFrame {
    ResultSet  resultSet;
    MetodosGeneralesDao metodosGeneralesDao;
    public prueba() {
        initComponents();
        metodosGeneralesDao=new MetodosGeneralesDao();
        cargaMateria();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void cargaMateria() {
        try {
            Conexion  cc = Conexion.getInstance();
            Connection cn=cc.Conectar();
            String sql ="select * from nombre_materia";
            Statement st =cn.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while(rs.next()){
              Materia mat = new Materia();
              mat.setIdMateria(rs.getInt("id1_nombre_materia"));
              mat.setNombreMateria(rs.getString("materia"));
              materiaCmb.addItem(mat);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        materiaCmb = new javax.swing.JComboBox();

        materiaCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "seleccione" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(materiaCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(materiaCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox materiaCmb;
    // End of variables declaration//GEN-END:variables
}
